### PR TITLE
[Bug]: Fix Assets not displaying due empty Host Url

### LINKED ISSUE #32: [Gotenberg] Additional Files (Images, CSS, JS) are not applied
When generating a PDF with additional files they are not applied in the result. It is obvious with Images, after the generation there is just the default no image icon and an outline where the image should have been. I've used the area bricks and templates from the demo project. But CSS Files are also not applied correctly as visible in the screenshots

**PDF Page in Editor**
CleanShot 2023-06-08 at 18 03 16

**Resulted PDF**
CleanShot 2023-06-08 at 18 03 26

I think this is because Gotenberg cannot handle additional files that are not sent via the api. At least I understand the documentation the way that [all additional files need to be send via the assets part](https://github.com/gotenberg/gotenberg-php#:~:text=the%20Stream%20class.-,You%20may%20also%20send%20additional%20files%2C%20like%20images%2C%20fonts%2C%20stylesheets%2C%20and%20so%20on.%20The%20only%20requirement%20is%20that%20their%20paths%20in%20the%20HTML%20DOM%20are%20on%20the%20root%20level.,-use%20Gotenberg%5C)

I've implemented a possible solution for the assets function and will create a pull request and link it to this issue. But I actually don't really like that solution as it is a little bit hacky so any input would be appreciated. With the implemented changes the pdf is generated correctly with all images and styles:

CleanShot 2023-06-08 at 18 14 57

### PR DESCRIPTION
**Pull request by kingjia90**
Fixes https://github.com/pimcore/web-to-print-bundle/issues/32

### CODE REVIEW

File: src/Processor/Gotenberg.php [hunk 1]
```diff
@@ -41,7 +41,7 @@ protected function buildPdf(PrintAbstract $document, object $config): string
         $html = $document->renderDocument($params);
 
         $params['hostUrl'] = 'http://nginx:80';
-        if (isset($web2printConfig['gotenbergHostUrl'])) {
+        if (isset($web2printConfig['gotenbergHostUrl']) && !empty($web2printConfig['gotenbergHostUrl'])) {
```
Comment (blankse) [inline src/Processor/Gotenberg.php]:
```suggestion
        if (!empty($web2printConfig['gotenbergHostUrl'])) {
```
empty() also cover isset()
