### PR TITLE
[Bug]: Fix missing perspective cfg

### LINKED ISSUE #17017: [Bug]: Option "Add print page" can't be disabled in context menu
### Pimcore version

11.2.3

### Steps to reproduce

If you create a perspective view to disable the option "Add print page" in the document context menu it still remains, always. No matter what the settings are.

Create a perspective and disable "Add print page":
perspective-config

Set the user and its roles to use this perspective, and open the backend with this user. The option is still available:
context-menu

I checked the network communication. In the page load the perspective config is also included. This config looks like it is configured in the backend before, but it has no effect. I tried the same with "add link" which work perfect.
network

### Actual Behavior

The option "Add print page" appear in the context menu always. 

### Expected Behavior

The option "Add print page" behaves like it's configured in the perspective config.

### PR DESCRIPTION
**Pull request by kingjia90**
Resolves https://github.com/pimcore/pimcore/issues/17017

### CODE REVIEW

**Comment by kingjia90** [comment]
draft: It doesn't work yet , here is always true
https://github.com/pimcore/admin-ui-classic-bundle/blob/1976b8f869ad450e1b3d2b9e4aebcc47f3487e7e/public/js/pimcore/perspective.js#L62-L64

File: public/js/startup.js [hunk 1]
```diff
@@ -40,6 +40,10 @@ pimcore.bundle.web2print.startup = Class.create({
         var menu = e.detail.menu;
         var tree = e.detail.tree;
         var me = this;
+        const perspectiveCfg = pimcore.globalmanager.get("perspective");
```
Comment (kingjia90) [inline public/js/startup.js:43]:
```suggestion
        const perspectiveCfg = e.detail.perspective;
```
and adding `perspective: perspectiveCfg` to
https://github.com/pimcore/admin-ui-classic-bundle/blob/558c7c245208793ed67a413eca86810d75fcb325/public/js/pimcore/document/tree.js#L867

would work
